apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: musa1-v1-0-0
    applicationId: app_ee1cfc91-25e6-41ae-bf8c-8baecae6b0d0
    version: v1.0.0
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    environmentId: env_7e4359f1-7e01-44ca-be19-88ac45dd97d7
  name: musa1-v1-0-0
spec:
  selector:
    app: musa1-v1-0-0
