apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: newmusatest1-main
      imagePullPolicy: Always
      imageRegistry: asd/newmusatest1
      imagePullSecretName: imagepull-docker
      credentialId: credential_bea82312-be7e-4e26-ad10-ac1524e8862b
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: newmusatest1
    version: v1.0.0
    applicationId: app_ff1ab00e-7188-43d8-b791-6a07f44a206f
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    environmentId: env_f3a0dede-1262-4950-a23a-fb94ef56c38d
    environmentName: MusaEnv9
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: newmusatest1
  serviceType: ClusterIP
  version: v1.0.0
  namespace: Musa
