apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: musatest2-main
      imagePullPolicy: Always
      imageRegistry: asd/asd123
      imagePullSecretName: imagepull-docker
      credentialId: credential_bea82312-be7e-4e26-ad10-ac1524e8862b
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: musatest2
    version: v1.0.0
    applicationId: app_6f16ee38-c727-4414-9a97-be095b2d05a0
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    environmentId: env_258ca8c1-d5ee-4fac-9b75-886f3fc9e52a
    environmentName: musaenv6
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: MusaTest2
  serviceType: ClusterIP
  version: v1.0.0
  namespace: Musa
