apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: musa1-v1-0-0
  labels:
    app: musa1-v1-0-0
    applicationId: app_ee1cfc91-25e6-41ae-bf8c-8baecae6b0d0
    version: v1.0.0
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    environmentId: env_cc5f7966-5961-4a2d-9788-b018b4caf8cf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musa1-v1-0-0
