apiVersion: v1
kind: Namespace
metadata:
  name: Musa
  labels:
    environmentId: env_38e01d30-58b7-46ca-bac4-97a277a11780
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    projectName: newmusatestproject
    environmentName: musaenv4
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    goldilocks.fairwinds.com/enabled: 'true'
