apiVersion: v1
kind: Namespace
metadata:
  name: Musa
  labels:
    environmentId: env_d1085ecc-ccb4-49d3-9bfc-b2c86679148c
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    projectName: newmusatestproject
    environmentName: musaenv3
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    goldilocks.fairwinds.com/enabled: 'true'
