apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: asd1-v1-0-0
  labels:
    app: asd1-v1-0-0
    applicationId: app_14a57454-064e-4c71-8bb5-197a72cd742d
    version: v1.0.0
    organizationId: org_214f8824-489e-4427-b043-83252b36ac2b
    projectId: project_e045038e-659d-446f-80a4-9ea25944f637
    environmentId: env_ca28e45d-4c25-4205-bbd7-5888957b786f
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asd1-v1-0-0
